basePath: /
definitions:
  api.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  app.CommResponse:
    properties:
      data: {}
      ret_code:
        type: string
      ret_desc:
        type: string
    type: object
  app.ErrResponse:
    properties:
      ret_code:
        type: string
      ret_desc:
        type: string
    type: object
  app.ListResponse:
    properties:
      data: {}
      ret_code:
        type: string
      ret_desc:
        type: string
      total:
        type: integer
    type: object
  model.Article:
    properties:
      content:
        type: string
      create_time:
        type: string
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      operator:
        type: string
      state:
        description: CoverImageUrl string    `gorm:"cover_image_url" json:"cover_image_url"`
        type: integer
      tags:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      update_time:
        type: string
    type: object
  model.Tag:
    properties:
      article_total:
        type: integer
      create_time:
        type: string
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      operator:
        type: string
      state:
        type: integer
      update_time:
        type: string
    type: object
  service.CreateArticleRequest:
    properties:
      content:
        type: string
      create_time:
        type: string
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      operator:
        type: string
      state:
        description: CoverImageUrl string    `gorm:"cover_image_url" json:"cover_image_url"`
        type: integer
      tags:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      update_time:
        type: string
    type: object
  service.CreateTagRequest:
    properties:
      article_total:
        type: integer
      create_time:
        type: string
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      operator:
        type: string
      state:
        type: integer
      update_time:
        type: string
    type: object
  service.UpdateArticleRequest:
    properties:
      content:
        type: string
      create_time:
        type: string
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      operator:
        type: string
      state:
        description: CoverImageUrl string    `gorm:"cover_image_url" json:"cover_image_url"`
        type: integer
      tags:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      update_time:
        type: string
    type: object
  service.UpdateTagRequest:
    properties:
      article_total:
        type: integer
      create_time:
        type: string
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      operator:
        type: string
      state:
        type: integer
      update_time:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a blog server restful api docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Blog Service API
  version: "1.0"
paths:
  /api/sys/config:
    get:
      description: 获取系统配置项，一般是key-value格式
      parameters:
      - description: 名称
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.CommResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 获取系统配置项
      tags:
      - Tag
  /api/v1/articles:
    get:
      description: 根据条件获取多个文章详细信息
      parameters:
      - description: 文章名称
        in: query
        name: name
        type: string
      - description: 状态
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/app.ListResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Article'
                  type: array
              type: object
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 获取多个文章
      tags:
      - Article
    post:
      consumes:
      - application/json
      description: 创建带标签的文章
      parameters:
      - description: 创建文章
        in: body
        name: CreateArticleRequest
        required: true
        schema:
          $ref: '#/definitions/service.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.CommResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 创建文章
      tags:
      - Article
  /api/v1/articles/{id}:
    delete:
      description: 删除文章
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.CommResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 删除文章
      tags:
      - Article
    get:
      consumes:
      - application/json
      description: 获取单个文章详细信息
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/app.CommResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.Article'
              type: object
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 获取单个文章
      tags:
      - Article
    put:
      consumes:
      - application/json
      description: 修改带标签的文章
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: 修改文章
        in: body
        name: UpdateArticleRequest
        required: true
        schema:
          $ref: '#/definitions/service.UpdateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.CommResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 修改文章
      tags:
      - Article
  /api/v1/tag:
    delete:
      description: 删除标签
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.CommResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 删除标签
      tags:
      - Tag
    post:
      consumes:
      - application/json
      description: 创建标签
      parameters:
      - description: 创建标签
        in: body
        name: CreateTagRequest
        required: true
        schema:
          $ref: '#/definitions/service.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.CommResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 创建标签
      tags:
      - Tag
    put:
      consumes:
      - application/json
      description: 修改标签
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      - description: 修改文章
        in: body
        name: UpdateTagRequest
        required: true
        schema:
          $ref: '#/definitions/service.UpdateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.CommResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 修改标签
      tags:
      - Tag
  /api/v1/tags:
    get:
      description: 获取多个标签
      parameters:
      - description: 标签名称
        in: query
        name: name
        type: string
      - description: 状态
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page_num
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/app.ListResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Tag'
                  type: array
              type: object
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 获取多个标签
      tags:
      - Tag
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: 获取登录用户信息
      parameters:
      - description: 用户信息
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.CommResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      security:
      - JWT: []
      summary: 用户信息
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: 请求鉴权获取Token
      parameters:
      - description: 用户信息
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.CommResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/app.ErrResponse'
      summary: 鉴权接口
      tags:
      - Auth
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
